/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaceblastica;

import java.sql.SQLException;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Dicente
 */
public class CadForn extends javax.swing.JInternalFrame {
    final String banco = "jdbc:mysql://localhost/dbpowerguido";
    final String usuario = "root";
    final String senha = "";
    String user;
    Connection conexao;
    PreparedStatement sql;
    ResultSet resultado;
    /**
     * Creates new form CadCli
     */
    public CadForn() throws SQLException {
        this.conexao = DriverManager.getConnection(banco,usuario,senha);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbNome = new javax.swing.JLabel();
        lbCNPJ = new javax.swing.JLabel();
        tfCNPJ = new javax.swing.JTextField();
        tfNome = new javax.swing.JTextField();
        btSalvar = new javax.swing.JToggleButton();
        btNovo = new javax.swing.JToggleButton();
        btAlterar = new javax.swing.JToggleButton();
        btConsultar = new javax.swing.JButton();
        lbMsg = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        btExcluir = new javax.swing.JButton();
        tfEmail = new javax.swing.JTextField();

        setClosable(true);

        lbNome.setText("Nome:");

        lbCNPJ.setText("CNPJ:");

        tfCNPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCNPJActionPerformed(evt);
            }
        });

        tfNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeActionPerformed(evt);
            }
        });

        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btNovo.setText("Novo");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });

        btAlterar.setText("Alterar");
        btAlterar.setEnabled(false);
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        btConsultar.setText("Consultar");
        btConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarActionPerformed(evt);
            }
        });

        lbMsg.setText(" ");

        lbEmail.setText("Email:");

        btExcluir.setText("Excluir");
        btExcluir.setEnabled(false);
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        tfEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEmailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btSalvar)
                        .addGap(25, 25, 25)
                        .addComponent(btAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btExcluir)
                        .addGap(25, 25, 25)
                        .addComponent(btNovo))
                    .addComponent(lbMsg)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbEmail)
                        .addGap(23, 23, 23)
                        .addComponent(tfEmail))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbNome)
                        .addGap(20, 20, 20)
                        .addComponent(tfNome))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbCNPJ)
                        .addGap(22, 22, 22)
                        .addComponent(tfCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btConsultar)))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btConsultar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNome)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEmail)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(lbMsg)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btExcluir)
                    .addComponent(btNovo)
                    .addComponent(btAlterar)
                    .addComponent(btSalvar))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        try {
            sql = conexao.prepareStatement("update fornecedor set nome=?,cnpj=?,email=? where cnpj='"+user+"'");
            sql.setString(1, tfNome.getText());
            sql.setString(2, tfCNPJ.getText());
            sql.setString(3, tfEmail.getText());
            sql.executeUpdate();
            lbMsg.setText ("Alterado com sucesso!");
        } catch (SQLException ex) {
            Logger.getLogger(CadForn.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btAlterarActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        try {
            sql = conexao.prepareStatement("insert into fornecedor(nome,cnpj,email) values(?,?,?)");
            sql.setString(1, tfNome.getText());
            sql.setString(2, tfCNPJ.getText());
            sql.setString(3, tfEmail.getText());
            sql.executeUpdate();
            lbMsg.setText ("Cadastrado com sucesso!");
        } catch (SQLException ex) {
            Logger.getLogger(CadForn.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        tfCNPJ.setText(null);
        tfNome.setText(null);
        tfEmail.setText(null);
        btSalvar.setEnabled(true);
        btAlterar.setEnabled(false);
        btExcluir.setEnabled(false);
        lbMsg.setText (" ");
    }//GEN-LAST:event_btNovoActionPerformed

    private void btConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarActionPerformed
        try {
            tfNome.setText(null);
            tfEmail.setText(null);
            sql = conexao.prepareStatement("select * from fornecedor where cnpj=?");
            sql.setString(1, tfCNPJ.getText());
            resultado = sql.executeQuery();
            if(resultado!=null && resultado.next()){
                tfNome.setText(resultado.getString("nome"));
                tfEmail.setText(resultado.getString("email"));
                user = resultado.getString("cnpj");
                lbMsg.setText(" ");
                btAlterar.setEnabled(true);
                btSalvar.setEnabled(false);
                btExcluir.setEnabled(true);
            }else{
                lbMsg.setText("CPNJ inexistente!");
            }
        } catch (SQLException ex) {
            Logger.getLogger(CadForn.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btConsultarActionPerformed

    private void tfCNPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCNPJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCNPJActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        try {
            tfCNPJ.setText(null);
            tfNome.setText(null);
            tfEmail.setText(null);
            btSalvar.setEnabled(true);
            btAlterar.setEnabled(false);
            btExcluir.setEnabled(false);
            sql = conexao.prepareStatement("delete from fornecedor where cnpj='"+user+"'");
            sql.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(CadForn.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void tfEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEmailActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btAlterar;
    private javax.swing.JButton btConsultar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JToggleButton btNovo;
    private javax.swing.JToggleButton btSalvar;
    private javax.swing.JLabel lbCNPJ;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbMsg;
    private javax.swing.JLabel lbNome;
    private javax.swing.JTextField tfCNPJ;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfNome;
    // End of variables declaration//GEN-END:variables
}
