/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaceblastica;

import java.sql.SQLException;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Dicente
 */
public class CadProd extends javax.swing.JInternalFrame {
    final String banco = "jdbc:mysql://localhost/dbpowerguido";
    final String usuario = "root";
    final String senha = "";
    String nomeP;
    Connection conexao;
    PreparedStatement sql;
    ResultSet resultado;
    /**
     * Creates new form CadCli
     */
    public CadProd() throws SQLException {
        this.conexao = DriverManager.getConnection(banco,usuario,senha);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbPreco = new javax.swing.JLabel();
        lbNome = new javax.swing.JLabel();
        lbQtd = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        tfPreco = new javax.swing.JTextField();
        btSalvar = new javax.swing.JToggleButton();
        btNovo = new javax.swing.JToggleButton();
        btAlterar = new javax.swing.JToggleButton();
        btConsultar = new javax.swing.JButton();
        lbMsg = new javax.swing.JLabel();
        tfDesc = new javax.swing.JTextField();
        tfMarca = new javax.swing.JTextField();
        lbDesc = new javax.swing.JLabel();
        lbMarca = new javax.swing.JLabel();
        btExcluir = new javax.swing.JButton();
        tfQtd = new javax.swing.JTextField();
        lbMod = new javax.swing.JLabel();
        tfMod = new javax.swing.JTextField();

        setClosable(true);

        lbPreco.setText("Preço:");

        lbNome.setText("Nome:");

        lbQtd.setText("Qtd:");

        tfNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeActionPerformed(evt);
            }
        });

        tfPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPrecoActionPerformed(evt);
            }
        });

        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btNovo.setText("Novo");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });

        btAlterar.setText("Alterar");
        btAlterar.setEnabled(false);
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        btConsultar.setText("Consultar");
        btConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarActionPerformed(evt);
            }
        });

        lbMsg.setText(" ");

        tfDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDescActionPerformed(evt);
            }
        });

        lbDesc.setText("Descrição:");

        lbMarca.setText("Marca:");

        btExcluir.setText("Excluir");
        btExcluir.setEnabled(false);
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        lbMod.setText("Modelo:");

        tfMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfModActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btSalvar)
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btAlterar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btExcluir))
                            .addComponent(lbMsg))
                        .addGap(25, 25, 25)
                        .addComponent(btNovo))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbMarca)
                            .addComponent(lbDesc)
                            .addComponent(lbQtd)
                            .addComponent(lbPreco)
                            .addComponent(lbNome)
                            .addComponent(lbMod))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfMod, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btConsultar))
                                .addComponent(tfPreco)
                                .addComponent(tfDesc)
                                .addComponent(tfMarca)
                                .addComponent(tfQtd)))))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNome, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btConsultar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPreco)
                    .addComponent(tfPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbQtd)
                    .addComponent(tfQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDesc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMarca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMod)
                    .addComponent(tfMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(lbMsg)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btExcluir)
                    .addComponent(btNovo)
                    .addComponent(btAlterar)
                    .addComponent(btSalvar))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPrecoActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        try {
            sql = conexao.prepareStatement("update produto set nome=?,preco=?,qtd=?,desc=?,marca=?,modelo=? where nome='"+nomeP+"'");
            sql.setString(1, tfNome.getText());
            sql.setDouble(2, Double.parseDouble(tfPreco.getText()));
            sql.setInt(3, Integer.parseInt(tfQtd.getText()));
            sql.setString(4, tfDesc.getText());
            sql.setString(5, tfMarca.getText());
            sql.setString(6, tfMod.getText());
            sql.executeUpdate();
            lbMsg.setText ("Alterado com sucesso!");
        } catch (SQLException ex) {
            Logger.getLogger(CadProd.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btAlterarActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        try {
            sql = conexao.prepareStatement("insert into produto(nome,preco,qtd,descricao,marca,modelo) values(?,?,?,?,?,?)");
            sql.setString(1, tfNome.getText());
            sql.setDouble(2, Double.parseDouble(tfPreco.getText()));
            sql.setInt(3, Integer.parseInt(tfQtd.getText()));
            sql.setString(4, tfDesc.getText());
            sql.setString(5, tfMarca.getText());
            sql.setString(6, tfMod.getText());
            sql.executeUpdate();
            lbMsg.setText ("Cadastrado com sucesso!");
        } catch (SQLException ex) {
            Logger.getLogger(CadProd.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        tfNome.setText(null);
        tfPreco.setText(null);
        tfQtd.setText(null);
        tfDesc.setText(null);
        tfMarca.setText(null);
        tfMod.setText(null);
        btSalvar.setEnabled(true);
        btAlterar.setEnabled(false);
        btExcluir.setEnabled(false);
        lbMsg.setText (" ");
    }//GEN-LAST:event_btNovoActionPerformed

    private void btConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarActionPerformed
        try {
            tfPreco.setText(null);
            tfQtd.setText(null);
            tfDesc.setText(null);
            tfMarca.setText(null);
            tfMod.setText(null);
            sql = conexao.prepareStatement("select * from produto where nome=?");
            sql.setString(1, tfNome.getText());
            resultado = sql.executeQuery();
            if(resultado!=null && resultado.next()){
                tfQtd.setText(String.valueOf(resultado.getInt("qtd")));
                tfMod.setText(resultado.getString("modelo"));
                tfPreco.setText(String.valueOf(resultado.getDouble("preco")));
                tfMarca.setText(resultado.getString("marca"));
                tfDesc.setText(resultado.getString("descricao"));
                nomeP = resultado.getString("nome");
                lbMsg.setText(" ");
                btAlterar.setEnabled(true);
                btSalvar.setEnabled(false);
                btExcluir.setEnabled(true);
            } else {
                lbMsg.setText("Produto inexistente!");
            }
        } catch (SQLException ex) {
            Logger.getLogger(CadProd.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btConsultarActionPerformed

    private void tfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeActionPerformed

    private void tfDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDescActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDescActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        try {
            tfNome.setText(null);
            tfPreco.setText(null);
            tfQtd.setText(null);
            tfDesc.setText(null);
            tfMarca.setText(null);
            tfMod.setText(null);
            btSalvar.setEnabled(true);
            btAlterar.setEnabled(false);
            btExcluir.setEnabled(false);
            sql = conexao.prepareStatement("delete from produto where nome='"+nomeP+"'");
            sql.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(CadProd.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void tfModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfModActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfModActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btAlterar;
    private javax.swing.JButton btConsultar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JToggleButton btNovo;
    private javax.swing.JToggleButton btSalvar;
    private javax.swing.JLabel lbDesc;
    private javax.swing.JLabel lbMarca;
    private javax.swing.JLabel lbMod;
    private javax.swing.JLabel lbMsg;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbPreco;
    private javax.swing.JLabel lbQtd;
    private javax.swing.JTextField tfDesc;
    private javax.swing.JTextField tfMarca;
    private javax.swing.JTextField tfMod;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfPreco;
    private javax.swing.JTextField tfQtd;
    // End of variables declaration//GEN-END:variables
}
