/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaceblastica;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Afran
 */
public class ConsC extends javax.swing.JInternalFrame {
    final String banco = "jdbc:mysql://localhost/dbpowerguido";
    final String usuario = "root";
    final String senha = "";
    String user;
    Connection conexao;
    PreparedStatement sql;
    ResultSet resultado;
    public ConsC() throws SQLException {
        this.conexao = DriverManager.getConnection(banco,usuario,senha);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbC = new javax.swing.JTable();
        cbCampo = new javax.swing.JComboBox<>();
        tfCons = new javax.swing.JTextField();
        btCons = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(245, 245, 245));
        setClosable(true);
        setVisible(false);

        tbC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "COD", "Funcionário", "Fornecedor", "Produto", "Marca", "Cod P.", "Preço", "Qtd", "Total", "Data"
            }
        ));
        tbC.setGridColor(new java.awt.Color(230, 230, 230));
        jScrollPane1.setViewportView(tbC);
        if (tbC.getColumnModel().getColumnCount() > 0) {
            tbC.getColumnModel().getColumn(0).setPreferredWidth(45);
            tbC.getColumnModel().getColumn(1).setPreferredWidth(130);
            tbC.getColumnModel().getColumn(2).setPreferredWidth(130);
            tbC.getColumnModel().getColumn(3).setPreferredWidth(130);
            tbC.getColumnModel().getColumn(4).setPreferredWidth(125);
            tbC.getColumnModel().getColumn(5).setPreferredWidth(60);
            tbC.getColumnModel().getColumn(6).setPreferredWidth(75);
            tbC.getColumnModel().getColumn(7).setPreferredWidth(35);
            tbC.getColumnModel().getColumn(8).setPreferredWidth(60);
            tbC.getColumnModel().getColumn(9).setPreferredWidth(90);
        }

        cbCampo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código", "Produto", "Funcionário", "Código P.", "Fornecedor", "CNPJ do F." }));

        btCons.setText("Consultar");
        btCons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Stay Classy SLDT", 1, 48)); // NOI18N
        jLabel1.setText("Compras");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cbCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfCons, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btCons)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(273, 273, 273)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCons))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btConsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsActionPerformed
        try {
            String campo = cbCampo.getSelectedItem().toString();
            DefaultTableModel model = (DefaultTableModel) tbC.getModel();
            switch(campo){
                case "Produto":
                sql = conexao.prepareStatement("select * from produto as a,compra as b, produto_compra as c, fornecedor as d, usuario as f where f.cod = b.cod_user and a.cod = c.cod_prod and b.cod = c.cod_compra and d.cod = c.cod_forn and a.nome like '%"+tfCons.getText()+"%' order by b.cod");
                resultado = sql.executeQuery();
                model.setNumRows(0);
                while(resultado.next()){
                    model.addRow(new Object[]{resultado.getInt("b.cod"),resultado.getString("f.nome"),resultado.getString("d.nome"),resultado.getString("a.nome"),resultado.getString("a.marca"),resultado.getInt("a.cod"),resultado.getDouble("a.preco"),resultado.getInt("c.qt"),resultado.getDouble("a.preco")*resultado.getInt("c.qt"),resultado.getString("b.data")});
                }break;
                case "Código":
                sql = conexao.prepareStatement("select * from produto as a,compra as b, produto_compra as c, fornecedor as d, usuario as f where f.cod = b.cod_user and a.cod = c.cod_prod and b.cod = c.cod_compra and d.cod = c.cod_forn and b.cod = "+tfCons.getText()+" order by b.cod");
                resultado = sql.executeQuery();
                model.setNumRows(0);
                while(resultado.next()){
                    model.addRow(new Object[]{resultado.getInt("b.cod"),resultado.getString("f.nome"),resultado.getString("d.nome"),resultado.getString("a.nome"),resultado.getString("a.marca"),resultado.getInt("a.cod"),resultado.getDouble("a.preco"),resultado.getInt("c.qt"),resultado.getDouble("a.preco")*resultado.getInt("c.qt"),resultado.getString("b.data")});
                }break;
                case "Código P.":
                sql = conexao.prepareStatement("select * from produto as a,compra as b, produto_compra as c, fornecedor as d, usuario as f where f.cod = b.cod_user and a.cod = c.cod_prod and b.cod = c.cod_compra and d.cod = c.cod_forn and a.cod = "+tfCons.getText()+" order by b.cod");
                resultado = sql.executeQuery();
                model.setNumRows(0);
                while(resultado.next()){
                    model.addRow(new Object[]{resultado.getInt("b.cod"),resultado.getString("f.nome"),resultado.getString("d.nome"),resultado.getString("a.nome"),resultado.getString("a.marca"),resultado.getInt("a.cod"),resultado.getDouble("a.preco"),resultado.getInt("c.qt"),resultado.getDouble("a.preco")*resultado.getInt("c.qt"),resultado.getString("b.data")});
                }break;
                case "Fornecedor":
                sql = conexao.prepareStatement("select * from produto as a,compra as b, produto_compra as c, fornecedor as d, usuario as f where f.cod = b.cod_user and a.cod = c.cod_prod and b.cod = c.cod_compra and d.cod = c.cod_forn and d.nome like '%"+tfCons.getText()+"%' order by b.cod");
                resultado = sql.executeQuery();
                model.setNumRows(0);
                while(resultado.next()){
                    model.addRow(new Object[]{resultado.getInt("b.cod"),resultado.getString("f.nome"),resultado.getString("d.nome"),resultado.getString("a.nome"),resultado.getString("a.marca"),resultado.getInt("a.cod"),resultado.getDouble("a.preco"),resultado.getInt("c.qt"),resultado.getDouble("a.preco")*resultado.getInt("c.qt"),resultado.getString("b.data")});
                }break;
                case "CNPJ do F.":
                sql = conexao.prepareStatement("select * from produto as a,compra as b, produto_compra as c, fornecedor as d, usuario as f where f.cod = b.cod_user and a.cod = c.cod_prod and b.cod = c.cod_compra and d.cod = c.cod_forn and d.cnpj = "+tfCons.getText()+" order by b.cod");
                resultado = sql.executeQuery();
                model.setNumRows(0);
                while(resultado.next()){
                    model.addRow(new Object[]{resultado.getInt("b.cod"),resultado.getString("f.nome"),resultado.getString("d.nome"),resultado.getString("a.nome"),resultado.getString("a.marca"),resultado.getInt("a.cod"),resultado.getDouble("a.preco"),resultado.getInt("c.qt"),resultado.getDouble("a.preco")*resultado.getInt("c.qt"),resultado.getString("b.data")});
                }break;
                case "Funcionário":
                sql = conexao.prepareStatement("select * from produto as a,compra as b, produto_compra as c, fornecedor as d, usuario as f where f.cod = b.cod_user and a.cod = c.cod_prod and b.cod = c.cod_compra and d.cod = c.cod_forn and f.nome like '%"+tfCons.getText()+"%' order by b.cod");
                resultado = sql.executeQuery();
                model.setNumRows(0);
                while(resultado.next()){
                    model.addRow(new Object[]{resultado.getInt("b.cod"),resultado.getString("f.nome"),resultado.getString("d.nome"),resultado.getString("a.nome"),resultado.getString("a.marca"),resultado.getInt("a.cod"),resultado.getDouble("a.preco"),resultado.getInt("c.qt"),resultado.getDouble("a.preco")*resultado.getInt("c.qt"),resultado.getString("b.data")});
                }break;
            }
        } catch (SQLException ex) {
            Logger.getLogger(ConsC.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btConsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCons;
    private javax.swing.JComboBox<String> cbCampo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbC;
    private javax.swing.JTextField tfCons;
    // End of variables declaration//GEN-END:variables
}
