/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaceblastica;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author Afran
 */
public class InfoF extends javax.swing.JInternalFrame {
    final String banco = "jdbc:mysql://localhost/dbpowerguido";
    final String user = "root";
    final String senha = "";
    Connection conexao;
    PreparedStatement sql;
    ResultSet resultado;
    Integer codU,qtV,qtC;
    String nome,login,email,cpf;
    public InfoF() throws SQLException {
        this.conexao = DriverManager.getConnection(banco,user,senha);
        initComponents();
    }
    
    public InfoF(Integer codU) throws SQLException {
        this.conexao = DriverManager.getConnection(banco,user,senha);
        this.codU = codU;
        sql = conexao.prepareStatement("select a.cod,a.nome,a.login,a.email,a.cpf,count(c.cod_user) from usuario as a, compra as c where a.cod = c.cod_user and a.cod = ?");
        sql.setInt(1,codU);
        resultado = sql.executeQuery();
        if(resultado!=null && resultado.next()){
            nome = resultado.getString("a.nome");
            login = resultado.getString("a.login");
            email = resultado.getString("a.email");
            cpf = resultado.getString("a.cpf");
            qtC = resultado.getInt("count(c.cod_user)");
        }
        sql = conexao.prepareStatement("select count(*) from usuario as a, venda as b where a.cod = b.cod_user and a.cod = "+codU);
        resultado = sql.executeQuery();
        if(resultado!=null && resultado.next()){
            qtV = resultado.getInt("count(*)");
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lbLogin = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        lbCpf = new javax.swing.JLabel();
        lbQtV = new javax.swing.JLabel();
        lbCod = new javax.swing.JLabel();
        lbNome = new javax.swing.JLabel();
        lbQtC = new javax.swing.JLabel();
        btVoltar = new javax.swing.JButton();

        jLabel1.setText("Código:");

        jLabel2.setText("Nome:");

        jLabel3.setText("Login:");

        jLabel4.setText("Email:");

        jLabel5.setText("CPF:");

        jLabel6.setText("Vendas Registradas:");

        jLabel13.setText("Compras Registradas:");

        lbLogin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbLogin.setForeground(new java.awt.Color(0, 51, 255));
        lbLogin.setText(login);

        lbEmail.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbEmail.setForeground(new java.awt.Color(0, 51, 255));
        lbEmail.setText(email);

        lbCpf.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbCpf.setForeground(new java.awt.Color(0, 51, 255));
        lbCpf.setText(cpf);

        lbQtV.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbQtV.setForeground(new java.awt.Color(0, 51, 255));
        lbQtV.setText(String.valueOf(qtV));

        lbCod.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbCod.setForeground(new java.awt.Color(0, 51, 255));
        lbCod.setText(String.valueOf(codU));

        lbNome.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbNome.setForeground(new java.awt.Color(0, 51, 255));
        lbNome.setText(nome);

        lbQtC.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbQtC.setForeground(new java.awt.Color(0, 51, 255));
        lbQtC.setText(String.valueOf(qtC));

        btVoltar.setText("Voltar");
        btVoltar.setFocusPainted(false);
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbLogin))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbEmail))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbCpf))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbQtV))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbCod))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbNome))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbQtC))
                    .addComponent(btVoltar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbCod))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lbNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbLogin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lbEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lbCpf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lbQtV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(lbQtC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btVoltar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_btVoltarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lbCod;
    private javax.swing.JLabel lbCpf;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbLogin;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbQtC;
    private javax.swing.JLabel lbQtV;
    // End of variables declaration//GEN-END:variables
}
