/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaceblastica;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Dicente
 */
public class TelaPrincipal extends javax.swing.JFrame {
    Integer codU;
    public TelaPrincipal() {
        initComponents();
    }
    
    public TelaPrincipal(Integer codU) {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        this.codU = codU;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpArea = new javax.swing.JDesktopPane();
        lbBg = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnCad = new javax.swing.JMenu();
        mnCadUser = new javax.swing.JMenuItem();
        mnCadP = new javax.swing.JMenuItem();
        mnCadF = new javax.swing.JMenuItem();
        mnCadV = new javax.swing.JMenuItem();
        mnCadC = new javax.swing.JMenuItem();
        mnCons = new javax.swing.JMenu();
        mnConsUser = new javax.swing.JMenuItem();
        mnConsProduto = new javax.swing.JMenuItem();
        mnConsF = new javax.swing.JMenuItem();
        mnConsV = new javax.swing.JMenuItem();
        mnHistV = new javax.swing.JMenuItem();
        mnConsC = new javax.swing.JMenuItem();
        mnHistC = new javax.swing.JMenuItem();
        mnFuncionário = new javax.swing.JMenu();
        mnInfo = new javax.swing.JMenuItem();
        mnLogout = new javax.swing.JMenuItem();
        mnSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Black Geo-Spheres.jpg"))); // NOI18N
        lbBg.setText("jLabel1");

        dpArea.setLayer(lbBg, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout dpAreaLayout = new javax.swing.GroupLayout(dpArea);
        dpArea.setLayout(dpAreaLayout);
        dpAreaLayout.setHorizontalGroup(
            dpAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbBg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dpAreaLayout.setVerticalGroup(
            dpAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbBg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        mnCad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cad.png"))); // NOI18N
        mnCad.setText("Cadastro");
        mnCad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                mnCadFocusGained(evt);
            }
        });
        mnCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCadActionPerformed(evt);
            }
        });

        mnCadUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/func.png"))); // NOI18N
        mnCadUser.setText("Funcionário");
        mnCadUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCadUserActionPerformed(evt);
            }
        });
        mnCad.add(mnCadUser);

        mnCadP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/prod.png"))); // NOI18N
        mnCadP.setText("Produto");
        mnCadP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCadPActionPerformed(evt);
            }
        });
        mnCad.add(mnCadP);

        mnCadF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/forn.png"))); // NOI18N
        mnCadF.setText("Fornecedor");
        mnCadF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCadFActionPerformed(evt);
            }
        });
        mnCad.add(mnCadF);

        mnCadV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/venda.png"))); // NOI18N
        mnCadV.setText("Venda");
        mnCadV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCadVActionPerformed(evt);
            }
        });
        mnCad.add(mnCadV);

        mnCadC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/compras.png"))); // NOI18N
        mnCadC.setText("Compra");
        mnCadC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCadCActionPerformed(evt);
            }
        });
        mnCad.add(mnCadC);

        jMenuBar1.add(mnCad);

        mnCons.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cons.png"))); // NOI18N
        mnCons.setText("Consulta");

        mnConsUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/func.png"))); // NOI18N
        mnConsUser.setText("Funcionário");
        mnConsUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnConsUserActionPerformed(evt);
            }
        });
        mnCons.add(mnConsUser);

        mnConsProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/prod.png"))); // NOI18N
        mnConsProduto.setText("Produto");
        mnConsProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnConsProdutoActionPerformed(evt);
            }
        });
        mnCons.add(mnConsProduto);

        mnConsF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/forn.png"))); // NOI18N
        mnConsF.setText("Fornecedor");
        mnConsF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnConsFActionPerformed(evt);
            }
        });
        mnCons.add(mnConsF);

        mnConsV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/venda.png"))); // NOI18N
        mnConsV.setText("Venda");
        mnConsV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnConsVActionPerformed(evt);
            }
        });
        mnCons.add(mnConsV);

        mnHistV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/HistV.png"))); // NOI18N
        mnHistV.setText("Histórico de V.");
        mnHistV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnHistVActionPerformed(evt);
            }
        });
        mnCons.add(mnHistV);

        mnConsC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/compras.png"))); // NOI18N
        mnConsC.setText("Compra");
        mnConsC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnConsCActionPerformed(evt);
            }
        });
        mnCons.add(mnConsC);

        mnHistC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/HistC.png"))); // NOI18N
        mnHistC.setText("Histórico de C.");
        mnHistC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnHistCActionPerformed(evt);
            }
        });
        mnCons.add(mnHistC);

        jMenuBar1.add(mnCons);

        mnFuncionário.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/func.png"))); // NOI18N
        mnFuncionário.setText("Funcionário");
        mnFuncionário.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnFuncionárioMouseClicked(evt);
            }
        });
        mnFuncionário.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnFuncionárioActionPerformed(evt);
            }
        });

        mnInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/infoF.png"))); // NOI18N
        mnInfo.setText("Informações");
        mnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnInfoActionPerformed(evt);
            }
        });
        mnFuncionário.add(mnInfo);

        mnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Logout.png"))); // NOI18N
        mnLogout.setText("Logout");
        mnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLogoutActionPerformed(evt);
            }
        });
        mnFuncionário.add(mnLogout);

        jMenuBar1.add(mnFuncionário);

        mnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sair.png"))); // NOI18N
        mnSair.setText("Sair");
        mnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnSairMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpArea)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpArea)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnCadUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadUserActionPerformed
        try {
            CadUser cadUser = new CadUser();
            dpArea.add(cadUser);
            cadUser.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnCadUserActionPerformed

    private void mnCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadActionPerformed
        
        
        
    }//GEN-LAST:event_mnCadActionPerformed

    private void mnCadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mnCadFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_mnCadFocusGained

    private void mnConsUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnConsUserActionPerformed
        try {
            ConsUser consUser = new ConsUser();
            dpArea.add(consUser);
            consUser.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnConsUserActionPerformed

    private void mnFuncionárioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnFuncionárioMouseClicked
        
    }//GEN-LAST:event_mnFuncionárioMouseClicked

    private void mnCadPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadPActionPerformed
        try {
            CadProd cadProd = new CadProd();
            dpArea.add(cadProd);
            cadProd.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnCadPActionPerformed

    private void mnConsProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnConsProdutoActionPerformed
        try {
            ConsProd consProd = new ConsProd();
            dpArea.add(consProd);
            consProd.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnConsProdutoActionPerformed

    private void mnCadFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadFActionPerformed
        try {
            CadForn cadForn = new CadForn();
            dpArea.add(cadForn);
            cadForn.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnCadFActionPerformed

    private void mnConsFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnConsFActionPerformed
        try {
            ConsForn consForn = new ConsForn();
            dpArea.add(consForn);
            consForn.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnConsFActionPerformed

    private void mnCadVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadVActionPerformed
        try {
            CadV cadV = new CadV(codU);
            dpArea.add(cadV);
            cadV.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnCadVActionPerformed

    private void mnCadCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadCActionPerformed
        try {
            CadC cadC = new CadC(codU);
            dpArea.add(cadC);
            cadC.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnCadCActionPerformed

    private void mnFuncionárioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnFuncionárioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnFuncionárioActionPerformed

    private void mnSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnSairMouseClicked
        System.exit(0);
    }//GEN-LAST:event_mnSairMouseClicked

    private void mnConsVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnConsVActionPerformed
        try {
            ConsV tV = new ConsV();
            dpArea.add(tV);
            tV.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnConsVActionPerformed

    private void mnConsCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnConsCActionPerformed
        try {
            ConsC tC = new ConsC();
            dpArea.add(tC);
            tC.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnConsCActionPerformed

    private void mnHistVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnHistVActionPerformed
        try {
            ConsHistV tHistV = new ConsHistV();
            dpArea.add(tHistV);
            tHistV.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnHistVActionPerformed

    private void mnHistCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnHistCActionPerformed
        try {
            ConsHistC tHistC = new ConsHistC();
            dpArea.add(tHistC);
            tHistC.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnHistCActionPerformed

    private void mnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnInfoActionPerformed
        try {
            InfoF info = new InfoF(codU);
            dpArea.add(info);
            info.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnInfoActionPerformed

    private void mnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLogoutActionPerformed
        try {
            TelaLogin tl = new TelaLogin();
            tl.setVisible(true);
            setVisible(false);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dpArea;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lbBg;
    private javax.swing.JMenu mnCad;
    private javax.swing.JMenuItem mnCadC;
    private javax.swing.JMenuItem mnCadF;
    private javax.swing.JMenuItem mnCadP;
    private javax.swing.JMenuItem mnCadUser;
    private javax.swing.JMenuItem mnCadV;
    private javax.swing.JMenu mnCons;
    private javax.swing.JMenuItem mnConsC;
    private javax.swing.JMenuItem mnConsF;
    private javax.swing.JMenuItem mnConsProduto;
    private javax.swing.JMenuItem mnConsUser;
    private javax.swing.JMenuItem mnConsV;
    private javax.swing.JMenu mnFuncionário;
    private javax.swing.JMenuItem mnHistC;
    private javax.swing.JMenuItem mnHistV;
    private javax.swing.JMenuItem mnInfo;
    private javax.swing.JMenuItem mnLogout;
    private javax.swing.JMenu mnSair;
    // End of variables declaration//GEN-END:variables
}
