/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaceblastica;

/**
 *
 * @author Dicente
 */
import java.sql.SQLException;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
public class TelaLogin extends javax.swing.JFrame{
    final String banco = "jdbc:mysql://localhost/dbpowerguido";
    final String user = "root";
    final String senha = "";
    Connection conexao;
    PreparedStatement sql;
    ResultSet resultado;
    /**
     * Creates new form TelaLogin
     */
   
    public TelaLogin() throws SQLException {
        this.conexao = DriverManager.getConnection(banco,user,senha);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbLog = new javax.swing.JLabel();
        lbSen = new javax.swing.JLabel();
        tfLog = new javax.swing.JTextField();
        btEnt = new javax.swing.JButton();
        tfSen = new javax.swing.JPasswordField();
        lbResultado = new javax.swing.JLabel();
        lbCad1 = new javax.swing.JLabel();
        lbCad2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbLog.setText("Login:");

        lbSen.setText("Senha:");

        tfLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLogActionPerformed(evt);
            }
        });

        btEnt.setText("Entrar");
        btEnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEntActionPerformed(evt);
            }
        });
        btEnt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btEntKeyTyped(evt);
            }
        });

        lbResultado.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lbResultado.setForeground(new java.awt.Color(255, 30, 30));
        lbResultado.setText(" ");

        lbCad1.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        lbCad1.setText("Sem cadastro?");

        lbCad2.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        lbCad2.setForeground(new java.awt.Color(50, 100, 255));
        lbCad2.setText("Clique Aqui");
        lbCad2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbCad2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbLog)
                                .addGap(9, 9, 9)
                                .addComponent(tfLog, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbSen)
                                .addGap(4, 4, 4)
                                .addComponent(tfSen, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbCad1)
                                .addGap(3, 3, 3)
                                .addComponent(lbCad2))
                            .addComponent(lbResultado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btEnt)))
                .addGap(10, 10, 10))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {tfLog, tfSen});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLog)
                    .addComponent(tfLog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSen)
                    .addComponent(tfSen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(lbResultado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbCad1)
                            .addComponent(lbCad2)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btEnt)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btEntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEntActionPerformed
        try {
            sql=conexao.prepareStatement("select * from usuario where login=? and senha=?");
            sql.setString(1, tfLog.getText());
            sql.setString(2, String.valueOf(tfSen.getPassword()));
            resultado=sql.executeQuery();
            if (resultado!=null && resultado.next()){
                TelaPrincipal t = new TelaPrincipal(resultado.getInt("cod"));
                t.setVisible(true);
                setVisible(false);
                dispose();
            }else{
                lbResultado.setText("Usuário ou Senha Inválida");
            }
        } catch (SQLException ex) {
            Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btEntActionPerformed

    private void tfLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfLogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfLogActionPerformed

    private void lbCad2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCad2MouseClicked
        try {
            TelaCad c = new TelaCad();
            c.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lbCad2MouseClicked

    private void btEntKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btEntKeyTyped
        
    }//GEN-LAST:event_btEntKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TelaLogin().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEnt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbCad1;
    private javax.swing.JLabel lbCad2;
    private javax.swing.JLabel lbLog;
    private javax.swing.JLabel lbResultado;
    private javax.swing.JLabel lbSen;
    private javax.swing.JTextField tfLog;
    private javax.swing.JPasswordField tfSen;
    // End of variables declaration//GEN-END:variables
}
